// Build step: bundle runbooks/*.md into src/data/runbooks.ts (self-contained,
// stateless deploy). Mirrors cloudtech_rag/loader.py id extraction:
//   1) RB-002 style id in the filename stem
//   2) frontmatter `id:` / `doc_id:` in the first 200 chars
//   3) positional fallback RB-001...
//
// Usage: node scripts/build-data.mjs <runbooks-dir> <out-file.ts>

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

const ID_RE = /(?:^|[/_-])(RB|DOC)[-_]?(\d{3})/i;
const FM_RE = /^(?:id|doc[-_]?id)\s*[:=]\s*(RB[-_]\d{3})/im;

function extractId(name, text, index) {
  for (const candidate of [name, text.slice(0, 200)]) {
    const m = ID_RE.exec(candidate);
    if (m) return `${m[1].toUpperCase()}-${m[2]}`;
  }
  const fm = FM_RE.exec(text);
  if (fm) return fm[1].toUpperCase().replace("_", "-");
  return `RB-${String(index + 1).padStart(3, "0")}`;
}

function main() {
  const [dirArg, outArg] = process.argv.slice(2);
  if (!dirArg || !outArg) {
    console.error("usage: node scripts/build-data.mjs <runbooks-dir> <out-file.ts>");
    process.exit(1);
  }
  const dir = resolve(dirArg);
  const files = readdirSync(dir)
    .filter((f) => /\.(md|txt|markdown)$/i.test(f))
    .sort();
  if (files.length === 0) {
    console.error(`no .md/.txt files in ${dir}`);
    process.exit(1);
  }

  const docs = files.map((f, i) => {
    const text = readFileSync(join(dir, f), "utf8");
    return { id: extractId(basename(f, dirname(dir)), text, i), name: f, text };
  });

  const out = outArg.endsWith(".ts") ? outArg : `${outArg}.ts`;
  mkdirSync(dirname(resolve(out)), { recursive: true });
  const ts = `// AUTO-GENERATED by scripts/build-data.mjs — do not edit.
// Bundles the runbooks corpus into the Worker so the deploy is stateless.
import type { Doc } from "../types";

export const RUNBOOKS: Doc[] = ${JSON.stringify(docs, null, 2)};
`;
  writeFileSync(out, ts);
  console.log(`wrote ${docs.length} docs -> ${out}`);
}

main();