// Generates src/data/version.ts with the git commit + build time, so every
// deploy can be correlated back to the exact source revision (see GET /api/version
// and the X-Deploy-Commit response header).

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

let commit = "unknown";
try {
  commit = execSync("git rev-parse --short HEAD", { cwd: root, encoding: "utf-8" }).trim();
} catch {
  /* not a git checkout — fine, keep "unknown" */
}

const deployedAt = new Date().toISOString();
const content = `// GENERATED by scripts/build-version.mjs — do not edit.
export const VERSION = {
  commit: ${JSON.stringify(commit)},
  deployedAt: ${JSON.stringify(deployedAt)},
};
`;

writeFileSync(resolve(root, "src/data/version.ts"), content);
console.log(`version: commit=${commit} deployedAt=${deployedAt}`);