// Cloudflare Worker entry point.
//   GET  /                 -> static UI (served from ./public via ASSETS binding)
//   POST /api/answer       -> { "question": "..." }  => Answer JSON
//   GET  /api/answer?q=... -> same, for GET convenience
//   GET  /api/answer?q=...&debug=1 -> includes ranked diagnostics
//
// Fully stateless: the runbooks corpus is bundled at build time
// (src/data/runbooks.ts, generated by scripts/build-data.mjs).

import { Agent, docTitle } from "./agent.ts";
import { RUNBOOKS } from "./data/runbooks.ts";
import { VERSION } from "./data/version.ts";

let globalAgent: Agent | null = null;

function getAgent(): Agent {
  if (globalAgent === null) globalAgent = Agent.fromBundled();
  return globalAgent;
}

interface Env {
  ASSETS: Fetcher;
}

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

const JSON_HEADERS = { "Content-Type": "application/json; charset=utf-8", ...CORS };

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...JSON_HEADERS, "X-Deploy-Commit": VERSION.commit },
  });
}

// GET /api/version -> {commit, deployedAt, engine, corpus} so any deployed build
// can be correlated to the exact source revision in the repo.
function handleVersion(): Response {
  return json({
    commit: VERSION.commit,
    deployedAt: VERSION.deployedAt,
    engine: "hybrid lexical retrieval (TF-IDF cosine + token Jaccard + 3-gram Jaccard + service-grounding penalty)",
    corpus: { docs: RUNBOOKS.length, ids: RUNBOOKS.map((d) => d.id) },
  });
}

// GET  /api/docs        -> [{id, name, title}] for all bundled runbooks
// GET  /api/docs/:id    -> {id, name, title, text} for one runbook
function handleDocs(url: URL): Response {
  const m = url.pathname.match(/^\/api\/docs\/([^/]+)$/);
  if (m) {
    const id = decodeURIComponent(m[1]);
    const found = RUNBOOKS.find((d) => d.id === id) ?? RUNBOOKS.find((d) => d.name === id) ?? null;
    if (!found) return json({ error: "runbook not found" }, 404);
    return json({ id: found.id, name: found.name, title: docTitle(found.text), text: found.text });
  }
  return json(RUNBOOKS.map((d) => ({ id: d.id, name: d.name, title: docTitle(d.text) })));
}

async function handleAnswer(request: Request, debug: boolean): Promise<Response> {
  let question: string;
  const url = new URL(request.url);

  if (request.method === "GET") {
    question = url.searchParams.get("q") ?? "";
  } else {
    try {
      const body = (await request.json()) as { question?: unknown };
      question = typeof body.question === "string" ? body.question : "";
    } catch {
      return json({ error: "Expected JSON body: {\"question\": \"...\"}" }, 400);
    }
  }

  if (!question.trim()) {
    return json({ error: "`question` is required" }, 400);
  }

  const agent = getAgent();
  const answer = agent.answerQuestion(question);
  const payload: Record<string, unknown> = { ...answer };
  if (debug) payload.ranked = agent.diagnostics(question).slice(0, 5);
  return json(payload);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS });
    }

    if (url.pathname === "/api/answer") {
      return handleAnswer(request, url.searchParams.get("debug") === "1");
    }

    if (url.pathname === "/api/version") {
      return handleVersion();
    }

    if (url.pathname === "/api/docs" || url.pathname.startsWith("/api/docs/")) {
      return handleDocs(url);
    }

    // Everything else: serve the static UI from ./public (Pages-style).
    const res = await env.ASSETS.fetch(request);
    const headers = new Headers(res.headers);
    headers.set("X-Deploy-Commit", VERSION.commit);
    return new Response(res.body, { status: res.status, headers });
  },
};