// AUTO-GENERATED by scripts/build-data.mjs — do not edit.
// Bundles the runbooks corpus into the Worker so the deploy is stateless.
import type { Doc } from "../types";

export const RUNBOOKS: Doc[] = [
  {
    "id": "RB-001",
    "name": "RB-001.md",
    "text": "# checkout-api: High CPU\n\n## Overview\ncheckout-api handles order checkout traffic. High CPU usually means a sudden traffic spike or an inefficient hot path.\n\n## Symptoms\nSustained CPU >80% on checkout-api pods; latency p95 climbs; checkout timeouts.\n\n## Steps\n1. Check CPU dashboard and recent deploys in the last 2 hours.\n2. Confirm there is no stuck checkout loop (look for repeated order mutations).\n3. Check autoscaler target; scale up if traffic is legitimately high.\n4. Profile the hot path (perf) before making code changes.\n"
  },
  {
    "id": "RB-002",
    "name": "RB-002.md",
    "text": "# checkout-api: Too Many Connections\n\n## Overview\ncheckout-api uses Postgres with a shared connection pool. 'Too many connections' errors typically follow pool exhaustion.\n\n## Symptoms\nERROR: too many connections; checkout-api 503s; idle connections maxed.\n\n## Steps\n1. Check pool utilization and count of open Postgres connections.\n2. Increase pgbouncer max_client_conn and restart lookup.\n3. Look for a runaway migration holding locks or a long-running query.\n4. If a migration is the cause, pause it; kill blocked sessions.\n"
  },
  {
    "id": "RB-003",
    "name": "RB-003.md",
    "text": "# payments-api: High CPU\n\n## Overview\npayments-api authorizes and settles payments. High CPU is usually a retry storm from downstream providers or a hot code path.\n\n## Symptoms\nSustained CPU >80% on payments-api pods; settlement lag grows; provider timeouts.\n\n## Steps\n1. Check CPU dashboard and downstream provider latencies.\n2. Inspect retry loops on failed authorizations.\n3. Verify settlement batch sizes; they can explode under spike.\n4. Profile the hot path (perf) before changing code.\n"
  },
  {
    "id": "RB-004",
    "name": "RB-004.md",
    "text": "# payments-api: Too Many Connections\n\n## Overview\npayments-api shares the checkout cluster's Postgres. 'Too many connections' errors follow long-draining transactions during high volume.\n\n## Symptoms\nERROR: too many connections; payments-api 503s; settlement jobs fail.\n\n## Steps\n1. Check connection pool and long-running settlement transactions.\n2. Increase pool limits after confirming baseline.\n3. Kill stale sessions from failed settlement retries.\n4. Raise alert thresholds so retry storms drain.\n"
  },
  {
    "id": "RB-005",
    "name": "RB-005.md",
    "text": "# checkout-api: Safe Rollback\n\n## Overview\ncheckout-api ships via blue-green deploys. Rolls back are safe when DB migrations are backward-compatible.\n\n## Symptoms\nRegression found after a checkout-api deploy; need to revert quickly.\n\n## Steps\n1. Verify the migration in the target release is backward-compatible.\n2. Flip the canary/blue-green switch back to the previous build.\n3. Watch error rate and latency for 10 minutes.\n4. If schema changes are incompatible, open a data-fix ticket instead of reverting.\n"
  },
  {
    "id": "RB-006",
    "name": "RB-006.md",
    "text": "# payments-api: Safe Rollback\n\n## Overview\npayments-api also ships blue-green. Settlement sinks may already be drained, so check before reverting.\n\n## Symptoms\nRegression after a payments-api deploy; revert needed.\n\n## Steps\n1. Confirm no settlement sink was drained by the new build.\n2. Fall back to the previous payments-api build.\n3. Replay any drained settlement queue entries.\n4. Watch provider error rates for 10 minutes.\n"
  },
  {
    "id": "RB-007",
    "name": "RB-007.md",
    "text": "# inventory-api: Sync Lag\n\n## Overview\ninventory-api syncs stock levels from warehouse events. Lag appears when the event queue backs up.\n\n## Symptoms\nStock counts stale; sync lag reported on the inventory dashboard.\n\n## Steps\n1. Measure event queue depth and consumer throughput.\n2. Restart stuck consumers.\n3. If a processing bug is present, pause the pipeline at the source.\n4. Replay the event stream after the fix.\n"
  },
  {
    "id": "RB-008",
    "name": "RB-008.md",
    "text": "# inventory-api: High CPU\n\n## Overview\ninventory-api recomputes stock projections. High CPU usually means a runaway aggregation query on the stock table.\n\n## Symptoms\nSustained CPU >80% on inventory-api pods; projections delayed.\n\n## Steps\n1. Find the expensive aggregation query in the slow query log.\n2. Add the missing index on the stock table.\n3. Cap the projection recompute batch window.\n4. Kill any runaway recompute jobs still running.\n"
  },
  {
    "id": "RB-009",
    "name": "RB-009.md",
    "text": "# Deploy Freeze & Change Management\n\n## Overview\nChanges to checkout-api, payments-api and inventory-api are frozen during promotional windows unless approved.\n\n## Symptoms\nDeploy blocked by the freeze policy; need an exception.\n\n## Steps\n1. Check the freeze calendar for the current window.\n2. File a change request with risk assessment.\n3. Get explicit approval from the change advisory board.\n4. Schedule the deploy for the earliest approved slot.\n"
  },
  {
    "id": "RB-010",
    "name": "RB-010.md",
    "text": "# Incident Severity Definitions\n\n## Overview\nDefines severity levels. A severity-1 incident is a full customer-facing outage of a core service.\n\n## Symptoms\nCriteria for escalating an incident.\n\n## Steps\n1. Severity-1: core service (checkout, payments, inventory) fully down or data loss.\n2. Severity-2: major degradation, workaround available.\n3. Severity-3: non-urgent defect or minor degradation.\n4. Declare S1 immediately when customer impact is broad.\n"
  },
  {
    "id": "RB-011",
    "name": "RB-011.md",
    "text": "# Incident Postmortem 2026-08-10 (checkout-api outage)\n\n## Overview\nOn 2026-08-10 checkout-api was down for 47 minutes. Root cause was a deploy that shipped an incompatible DB migration; the fix was a rollback plus a data-fix ticket to reconcile dropped orders.\n\n## Symptoms\ncheckout-api 503s; orders stuck in 'processing'; payment links failed.\n\n## Steps\n1. Deploy 2026-08-10 09:12 pushed an incompatible migration.\n2. 09:18 error rates rose; incident declared at 09:21 (S1).\n3. 09:41 rollback executed; service restored 09:59.\n4. Follow-up: backward-compatibility gate added to the deploy pipeline; orders reconciled via data-fix queue.\n"
  },
  {
    "id": "RB-012",
    "name": "RB-012.md",
    "text": "# Customer Communication During Incidents\n\n## Overview\nGuidelines for communicating with customers during incidents. Customers are informed via the status page and email for S1/S2 incidents.\n\n## Symptoms\nCommunicating an ongoing incident to customers.\n\n## Steps\n1. Publish status-page update within 15 minutes of S1/S2 declaration.\n2. State impacted services, start time, and next update time.\n3. Post an update every 30 minutes until resolved.\n4. After resolution, send a postmortem summary email within 24h.\n"
  }
];
